"""Kickstarter Data Profiler
Automated profiling script for inspecting raw CSV assets across all source families.
Computes row counts, column types, distinct key cardinalities, and null distributions.
"""

import os
import sys
from pathlib import Path
import pandas as pd
from tabulate import tabulate

BASE_DIR = Path(r"D:\courses\Data Analysis 26-27\Projects\Kickstarter Projects\data")
RAW_DIR = BASE_DIR / "raw"
REPORT_PATH = Path(r"D:\courses\Data Analysis 26-27\Projects\Kickstarter Projects\docs\data_profiling_report.md")


def profile_file(file_path: Path, encoding: str = "utf-8", sample_size: int = 50000) -> dict:
    """Profiles an individual dataset file."""
    stats = {
        "File Name": file_path.name,
        "Size (MB)": round(file_path.stat().st_size / (1024 * 1024), 2),
        "Total Rows": 0,
        "Columns": 0,
        "Encoding": encoding,
        "Distinct IDs": "N/A",
        "Null Pct Avg": 0.0,
    }

    try:
        # Fast line count
        with open(file_path, "r", encoding=encoding, errors="ignore") as f:
            stats["Total Rows"] = sum(1 for _ in f) - 1

        # Read sample for schema statistics
        df = pd.read_csv(file_path, nrows=sample_size, encoding=encoding, on_bad_lines="skip", low_memory=False)
        stats["Columns"] = len(df.columns)
        stats["Null Pct Avg"] = round(df.isnull().mean().mean() * 100, 2)

        # ID detection
        id_cols = [c for c in df.columns if c.strip().lower() in ["id", "project_id"]]
        if id_cols:
            stats["Distinct IDs"] = f"{df[id_cols[0]].nunique():,} (in sample)"

    except Exception as e:
        stats["Error"] = str(e)

    return stats


def run_full_profiling():
    print("=" * 80)
    print("KICKSTARTER ANALYTICS ENGINEERING - DATA PROFILER")
    print("=" * 80)

    targets = [
        (RAW_DIR / "master_kickstarter" / "MasterKickstarter.csv", "utf-8"),
        (RAW_DIR / "master_kickstarter" / "County.csv", "utf-8"),
        (RAW_DIR / "master_kickstarter" / "Mapping.csv", "utf-8"),
        (RAW_DIR / "kickstarter_projects" / "ks-projects-201612.csv", "latin1"),
        (RAW_DIR / "kickstarter_projects" / "ks-projects-201801.csv", "utf-8"),
        (RAW_DIR / "WebRobots_Enrichment_Master.csv", "utf-8"),
    ]

    results = []
    for path, enc in targets:
        if path.exists():
            print(f"Profiling {path.name}...")
            results.append(profile_file(path, encoding=enc))
        else:
            print(f"[SKIP] Not found: {path.name}")

    if not results:
        print("No files were profiled.")
        return

    df_results = pd.DataFrame(results)
    table_str = tabulate(df_results, headers="keys", tablefmt="github", showindex=False)
    print("\n" + table_str)

    # Save Markdown report
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("# Automated Raw Data Profiling Report\n\n")
        f.write(f"Generated across primary datasets in `{RAW_DIR}`:\n\n")
        f.write(table_str)
        f.write("\n\n---\n*Report generated by `src/data_profiler.py`*\n")

    print(f"\nReport written to: {REPORT_PATH}")


if __name__ == "__main__":
    run_full_profiling()
